"""Equilibrium reference configs per temperature for point-to-set. T=0.5 loaded from the PT2 dataset;
higher T generated by swap MC (cheap and well-equilibrated above the supercooled regime). x_B recorded."""
import os, torch
from liquid_coupling_flow.ka_mcmc import make_species
from liquid_coupling_flow.ka_mcmc_fast import swap_mcmc_fast
from liquid_coupling_flow.ka_energy import ka_energy

PT2_N256 = "liquid_coupling_flow/artifacts/pt_ladder_hb_N256.pt"


def get_references(T, N, n_configs, device, out_dir, fracB=0.35):
    os.makedirs(out_dir, exist_ok=True)
    out = os.path.join(out_dir, f"refs_T{T}_N{N}.pt")
    L = (N / 1.2) ** 0.5
    if abs(T - 0.5) < 1e-9 and N == 256 and os.path.exists(PT2_N256):
        d = torch.load(PT2_N256, map_location="cpu", weights_only=False)
        x = d["configs_per_rung"][0][:n_configs].float(); s = d["s"].long()
    else:
        s = make_species(N, fracB).to(device)
        x, s = swap_mcmc_fast(N, L, T, s, device=device, n_chains=n_configs,
                              n_equil=4000, n_collect=1, every=1, step=0.05)
        x = x.cpu(); s = s.cpu()
    res = {"x": x, "s": s, "L": L, "T": T, "N": N, "xB": float((s == 1).float().mean())}
    torch.save(res, out)
    return res
